name: "FastAPI Serverless CI"

on:
  push:
    branches:
      - "main"

jobs:
  package_serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create a virtual env
        run: |
          python -m venv env

      - name: Install dependencies
        run: |
          . env/bin/activate
          python -m pip install -r ./src/requirements.txt -t ./src

      - name: Create application ZIP archive
        run: |
          cd ./src && zip -r functions.zip .

      - name: Upload functions.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'lamdbda-code-archive'
          path: ./src/functions.zip

  deploy:
    runs-on: ubuntu-latest
    needs: [ 'package_serverless' ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download functions.zip
        uses: actions/download-artifact@v4
        with:
          name: 'lamdbda-code-archive'

      - run: |
          du -h functions.zip
          aws --help

      # - name: Upload functions.zip to S3
      #   run: aws s3 functions.zip s3://bucket_name/functions.zip
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: Deploy to lambda
      #   run: aws lambda update-function-code --function-name my_function --s3-bucket bucket_name --s3-key functions.zip
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
